import "./globals.css";
import { Inter, Archivo, Gochi_Hand } from "next/font/google";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const archivo = Archivo({ subsets: ["latin"], variable: "--font-archivo" });
export const gochi = Gochi_Hand({
  weight: "400",
  variable: "--font-gochi",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${archivo.variable} ${gochi.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
